### ISSUE TITLE
Can't process sentences made up of words in a different order

### ISSUE THREAD

**Issue by 612twilight** [RandyPen/TextCluster#1]
从AINLP上看到推送了你的项目，项目有个bug，无法将不同顺序单词组成的句子归到同一类中，建议加入原有的聚类簇之后，不要break，只是不要再进行聚类类别判定或者新建，而对该样本的每个单词的p_bucket列表都加入该类，同时需要调整新建类别的逻辑，如果第一个单词匹配不通过，建立一个tmp词汇，将该单词放入，然后对下一个单词进行判定，直到所有的都不通过，才建立新的类别，并将tmp词汇里的p_bucket都加上这个新的类别。
以上

**Comment by RandyPen** [comment]
谢谢你的反馈，漏洞已修正。  
在测试文本中也增加了对应该特征的测试例句  
```
我是一头猪
一头猪是我
是我的一头猪
```

**Comment by 612twilight** [comment]
perfect！
