### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by lu161513** [RandyPen/TextCluster#2]
parser.add_argument('--threshold', type=float, default=0.3, help='Threshold for matching.')
这个threshold的作用是什么呀

**Comment by pencoa** [comment]
聚类的原理有点类似DBSCAN，直接由句子与团簇之间比较相似度来决定是否归到该团簇中。
threshold在这里是作为阈值，如果相似度达到该阈值，就归类。

**Comment by RandyPen** [comment]
聚类的原理类似DBSCAN，将新的句子与已有的团簇进行比较。如果相似度超过一个阈值，就划归到该团簇中。
threshold是相似度比较的阈值。
